<?php

/**
 * Implements hook_enable().
 */
function content_type_extras_enable() {
  // Weight content_type_extras to come after other modules -- in particular, field_group.
  db_update('system')
    ->fields(array('weight' => 10))
    ->condition('name', 'content_type_extras')
    ->condition('type', 'module')
    ->execute();
}

function content_type_extras_uninstall() {
  db_delete('variable')
    ->condition('name', 'content_type_extras_%', 'LIKE')
    ->execute();
}